### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by An-anson** [milindsoorya/blockchain-based-iov#2]
1) Contract: EthMessaging
       lastIndex
         When getting lastIndex, if no message has been sent to that address, 0 is returned:
     Error: Invalid number of arguments to Solidity function
      at Object.InvalidNumberOfSolidityArgs (node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:25:1)
      at SolidityFunction.validateArgs (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:74:1)
      at SolidityFunction.toPayload (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:90:1)
      at SolidityFunction.call (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:131:1)
      at SolidityFunction.execute (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:260:1)
      at node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:135:1
      at new Promise (<anonymous>)
      at node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:126:1
      at Context.<anonymous> (test/EthMessaging.js:78:26)

  2) Contract: EthMessaging
       lastIndex
         When a message is sent, lastIndex is increased:
     Error: invalid address
      at inputAddressFormatter (node_modules/truffle/build/webpack:/~/web3/lib/web3/formatters.js:274:1)
      at inputTransactionFormatter (node_modules/truffle/build/webpack:/~/web3/lib/web3/formatters.js:100:1)
      at node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:89:1
      at Array.map (<anonymous>)
      at Method.formatInput (node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:88:1)
      at Method.toPayload (node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:114:1)
      at Eth.send [as sendTransaction] (node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:139:1)
      at SolidityFunction.sendTransaction (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:173:1)
      at SolidityFunction.execute (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:256:1)
      at node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:204:1
      at new Promise (<anonymous>)
      at node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:155:1
      at Context.<anonymous> (test/EthMessaging.js:84:13)

  3) Contract: EthMessaging
       getLastMessage
         When getting last message, if address does not have any message, the transaction is reverted:
     AssertionError: Expected to fail with revert, but failed with: Error: Invalid number of arguments to Solidity function
      at fails (node_modules/truffle-assertions/index.js:130:13)
      at Context.<anonymous> (test/EthMessaging.js:97:13)

  4) Contract: EthMessaging
       getLastMessage
         When getting last message, last address message is returned:
     Error: invalid address
      at inputAddressFormatter (node_modules/truffle/build/webpack:/~/web3/lib/web3/formatters.js:274:1)
      at inputTransactionFormatter (node_modules/truffle/build/webpack:/~/web3/lib/web3/formatters.js:100:1)
      at node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:89:1
      at Array.map (<anonymous>)
      at Method.formatInput (node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:88:1)
      at Method.toPayload (node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:114:1)
      at Eth.send [as sendTransaction] (node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:139:1)
      at SolidityFunction.sendTransaction (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:173:1)
      at SolidityFunction.execute (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:256:1)
      at node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:204:1
      at new Promise (<anonymous>)
      at node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:155:1
      at Context.<anonymous> (test/EthMessaging.js:104:13)

  5) Contract: EthMessaging
       getMessageByIndex
         When getting message by index, if no message exists for that index the transaction is reverted:
     AssertionError: Expected to fail with revert, but failed with: Error: Invalid number of arguments to Solidity function
      at fails (node_modules/truffle-assertions/index.js:130:13)
      at Context.<anonymous> (test/EthMessaging.js:124:13)

  6) Contract: EthMessaging
       getMessageByIndex
         When getting message by index, address message related to that index is returned:
     Error: invalid address
      at inputAddressFormatter (node_modules/truffle/build/webpack:/~/web3/lib/web3/formatters.js:274:1)
      at inputTransactionFormatter (node_modules/truffle/build/webpack:/~/web3/lib/web3/formatters.js:100:1)
      at node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:89:1
      at Array.map (<anonymous>)
      at Method.formatInput (node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:88:1)
      at Method.toPayload (node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:114:1)
      at Eth.send [as sendTransaction] (node_modules/truffle/build/webpack:/~/web3/lib/web3/method.js:139:1)
      at SolidityFunction.sendTransaction (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:173:1)
      at SolidityFunction.execute (node_modules/truffle/build/webpack:/~/web3/lib/web3/function.js:256:1)
      at node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:204:1
      at new Promise (<anonymous>)
      at node_modules/truffle/build/webpack:/packages/truffle-contract/contract.js:155:1
      at Context.<anonymous> (test/EthMessaging.js:130:13)

**Comment by An-anson** [comment]
???

**Comment by An-anson** [comment]
try earlier version of Metamask
